### ISSUE TITLE
knife cs not working with chefdk 0.3.5

### ISSUE THREAD

**Issue by miguelaferreira** [CloudStack-extras/knife-cloudstack#110]
I've installed chefdk 0.3.5 and then installed knife-cloudstack using the chef environment:
```bash
> chef gem install knife-cloudstack
Successfully installed knife-cloudstack-0.0.17
Parsing documentation for knife-cloudstack-0.0.17
Installing ri documentation for knife-cloudstack-0.0.17
Done installing documentation for knife-cloudstack after 2 seconds
1 gem installed
```

Then tried to run it and got this stackstrace.
```bash
> knife cs
/opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2099:in `raise_if_conflicts': Unable to activate chef-11.6.2, because mixlib-config-2.1.0 conflicts with mixlib-config (>= 1.1.2, ~> 1.1), ohai-7.4.0 conflicts with ohai (< 7.0.0, >= 0.6.0), json-1.8.1 conflicts with json (<= 1.7.7, >= 1.4.4), net-ssh-multi-1.2.0 conflicts with net-ssh-multi (~> 1.1.0) (Gem::ConflictError)
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1282:in `activate'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:90:in `block in require'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:89:in `each'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:89:in `require'
	from /Users/mferreira/.chefdk/gem/ruby/2.1.0/gems/knife-cloudstack-0.0.17/lib/chef/knife/cs_baselist.rb:19:in `<top (required)>'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /Users/mferreira/.chefdk/gem/ruby/2.1.0/gems/knife-cloudstack-0.0.17/lib/chef/knife/cs_aag_list.rb:20:in `<top (required)>'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife/core/subcommand_loader.rb:37:in `load'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife/core/subcommand_loader.rb:37:in `block in load_commands'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife/core/subcommand_loader.rb:37:in `each'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife/core/subcommand_loader.rb:37:in `load_commands'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:120:in `load_commands'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:168:in `run'
	from /opt/chefdk/embedded/apps/chef/lib/chef/application/knife.rb:139:in `run'
	from /opt/chefdk/embedded/apps/chef/bin/knife:25:in `<top (required)>'
	from /opt/chefdk/bin/knife:33:in `load'
	from /opt/chefdk/bin/knife:33:in `<main>'
```

**Comment by miguelaferreira** [comment]
Apparently the gem in rubygems.org is outdated. I've fixed my knife-cloudstack by building the gem myself.
```bash
git clone https://github.com/CloudStack-extras/knife-cloudstack.git
cd knife-cloudstack
gem build knife-cloudstack.gemspec
gem install ./knife-cloudstack-*.gem
```
